### ISSUE TITLE
Invalid version: "1.1.1.2" on Mac OS

### ISSUE THREAD

**Issue by Tibus** [ShuttleLtd/Shuttle#2]
Hello, 
The version of a nodeJs package must have only 3 number so "version": "1.1.1.2" is not correct and crash on Mac Os. 
So no way to make it works on Mac os until the version is not fixed

**Comment by robjullian** [comment]
Thank you ;)

**Comment by robjullian** [comment]
Hey, I have a question. Its possible for you to build the .dmg installer ?
Thanks ;)

**Comment by Tibus** [comment]
Could we talk about it on facebook messenger? Just add me "Julien Delnatte"

**Comment by robjullian** [comment]
I don't have messenger but i have discord : Robin#3113
on peut parler en français si tu veux ;)
