### ISSUE TITLE
The url doesn't exists and why can't we see favicons

### ISSUE THREAD

**Issue by TheRolfFR** [ShuttleLtd/Shuttle#3]
Hello,
I had a problem is that the URL entered needs to be verified after submitting.
It should be cool to have website favicon in buttons rather than a color (that doesn't match on instagram).
I'll fix it.

**Comment by robjullian** [comment]
for the moment we don't add favicon because is not very beautiful, but we add the first letter of the title in the bubble

**Comment by robjullian** [comment]
thank you ;)
for the moment we don't add favicon because is not very beautiful, but we add the first letter of the title in the bubble

**Comment by TheRolfFR** [comment]
Ok. If you need help, I worked on my own on a exact similar project.

PS: je suis français

**Comment by robjullian** [comment]
ok, merci ;)
