### ISSUE TITLE
Icon's creation fails on some websites

### ISSUE THREAD

**Issue by KazeJiyu** [ShuttleLtd/Shuttle#7]
Hello !

When adding some website, the icon's creation fails, leading the circle to remain blank. I encountered this issue when adding [developpez.com](http://developpez.com).

This problem seems to come from `assets/main.js`, on line 255 : 

```javascript
getColors('https://www.google.com/s2/favicons?domain=' + link.toLowerCase()).then(colors => {
    url = "https://icons.better-idea.org/lettericons/"+matches[1].charAt(0).toUpperCase()+"-64-"+ colors[4].hex().substr(1).slice(0) +".png";
    ...
});
```
The call to `colors[4].hex()` raises an error because `colors[4]` is `undefined`.

I wanted to fix the problem and suggest a pull request, but I don't know this `getColors` method (I failed to find either source code or documentation) and I don't understand why you pick its fifth element specifically.

What do you think about this issue ?

**Comment by robjullian** [comment]
Hey, si tu veux la doc pour la fonction "getColor" regarde la : https://www.npmjs.com/package/get-image-colors

Le problème avec les ronds blancs est très connu, ça arrive quand le favicon est trop petit (l'api de googler ne donne pas de très bonnes résolutions des favicon). pour le moment nous avons qu'une seule solution, c'est d'ajouter la couleur des sites manuellement ici : https://github.com/ShuttleLtd/Shuttle/blob/master/assets/colors.json

**Comment by KazeJiyu** [comment]
Merci pour le lien, je cherchais du côté de [color-thief](https://github.com/lokesh/color-thief) !

D'accord, je l'ignorais. Désolé si certaines de mes interrogations sont un peu naïves : je suis plutôt _back-end_ et n'ai qu'une expérience modeste en développement web.

Quoi qu'il en soit, je pense que l'on peut améliorer ce problème. Actuellement la fonction plante, et l'icône est complètement vide (il n'y a donc même pas l'initiale du site). En remplaçant les lignes fautives par : 
```javascript
getColors('https://www.google.com/s2/favicons?domain=' + link.toLowerCase()).then(colors => {
    var color = colors[4] == undefined ? colors[0] : colors[4]
    url = "https://icons.better-idea.org/lettericons/"+matches[1].charAt(0).toUpperCase()+"-64-"+ color.hex().substr(1).slice(0) +".png";
```
le programme peut continuer normalement et l'icône pour [developpez.com](http://developpez.com) devient maintenant un "D" dans un cercle bleu sombre. C'est déjà mieux !

Je pense que l'idéal serait de prendre en considération la possibilité qu'aucune couleur ne puisse être trouvée pour un site et, dans ce cas, d'attribuer une couleur par défaut. Ainsi, l'application ne lève pas d'erreur et une icône est bien affichée pour l'utilisateur.

Je vais essayer de voir comment on peut faire assez proprement. Tu voudras que je soumette une PR ?

**Comment by robjullian** [comment]
Ton idée m'a l'aire bonne, sa serai vraiment cool que tu puisses me faire une PR :D
Merci ;)
